name: Build, Push, and Release Docker Container to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        APP_NAME: ${{ secrets.RENDER_APP_NAME }}
      run: |
        IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        curl --request GET \
        --url 'https://api.render.com/v1/owners?name=california-house-pricing&email=nandinichatterjee2003%40gmail.com&limit=20' \
        --header 'accept: application/json' \
        --header 'authorization: Bearer rnd_xmmy4zvYJ9i8AL4Z7fUqR4fF3jQ8'
