name: Build, Push, and Release Docker Container to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/brainvoid-nc/IMAGE_NAME:latest

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        APP_NAME: ${{ secrets.RENDER_APP_NAME }}
      run: |
        curl --request POST \
          --url "https://api.render.com/v1/services/${{ secrets.RENDER_APP_NAME }}/deploys" \
          --header "Accept: application/json" \
          --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          --header "Content-Type: application/json"
